import {
  MetricItem,
  SentimentDataPoint,
  TrendItem,
  DemographicRegion,
  InfluenceNode,
  InfluenceEdge,
  SocialPost,
  ForecastPoint,
} from './types';

export const mockMetrics: MetricItem[] = [
  {
    id: 'mentions',
    label: 'TOTAL MENTIONS',
    value: 148290,
    displayFormat: 'compact',
    changePercent: 14.8,
    changeType: 'increase',
    subtext: '+19.2k more than yesterday',
    trendData: [42, 48, 45, 53, 58, 62, 70, 68, 74, 82, 89, 95],
  },
  {
    id: 'sentiment',
    label: 'AUDIENCE MOOD (SENTIMENT)',
    value: 78.4,
    suffix: '%',
    displayFormat: 'decimal',
    changePercent: 5.2,
    changeType: 'increase',
    subtext: '4 happy posts for every 1 complaint',
    trendData: [72, 71, 74, 73, 76, 75, 77, 76, 79, 78, 77, 78.4],
  },
  {
    id: 'trend',
    label: 'TOP TRENDING TOPIC',
    value: 48.6,
    prefix: '#',
    suffix: '% spike',
    displayFormat: 'percent',
    changePercent: 48.6,
    changeType: 'increase',
    subtext: '#SyntraIntelligence growing fastest',
    trendData: [15, 20, 18, 25, 30, 42, 55, 68, 78, 85, 92, 100],
  },
  {
    id: 'voices',
    label: 'INFLUENCERS TALKING',
    value: 2840,
    displayFormat: 'compact',
    changePercent: 8.3,
    changeType: 'increase',
    subtext: '142 top creators posted',
    trendData: [2100, 2150, 2240, 2380, 2450, 2520, 2600, 2690, 2730, 2790, 2810, 2840],
  },
];

export const mockSentimentTimeline: SentimentDataPoint[] = [
  { timestamp: '00:00', positive: 68, neutral: 22, negative: 10, netScore: 79, volume: 4200 },
  { timestamp: '02:00', positive: 65, neutral: 24, negative: 11, netScore: 77, volume: 3800 },
  { timestamp: '04:00', positive: 71, neutral: 20, negative: 9, netScore: 81, volume: 4100 },
  { timestamp: '06:00', positive: 74, neutral: 18, negative: 8, netScore: 83, volume: 6500 },
  { timestamp: '08:00', positive: 79, neutral: 15, negative: 6, netScore: 86, volume: 11200 },
  { timestamp: '10:00', positive: 82, neutral: 13, negative: 5, netScore: 88, volume: 15800 },
  { timestamp: '12:00', positive: 77, neutral: 16, negative: 7, netScore: 85, volume: 17400 },
  { timestamp: '14:00', positive: 76, neutral: 17, negative: 7, netScore: 84, volume: 16200 },
  { timestamp: '16:00', positive: 80, neutral: 14, negative: 6, netScore: 87, volume: 18900 },
  { timestamp: '18:00', positive: 84, neutral: 12, negative: 4, netScore: 90, volume: 20500 },
  { timestamp: '20:00', positive: 81, neutral: 14, negative: 5, netScore: 88, volume: 16800 },
  { timestamp: '22:00', positive: 78, neutral: 16, negative: 6, netScore: 86, volume: 12890 },
];

export const mockTrends: TrendItem[] = [
  {
    id: 't-1',
    rank: 1,
    name: '#SyntraIntelligence',
    category: 'Product & AI',
    mentions: 48920,
    changePercent: 64.2,
    sentiment: 'positive',
    sentimentScore: 92,
    velocity: 'very_high',
  },
  {
    id: 't-2',
    rank: 2,
    name: '#NextGenAnalytics',
    category: 'Industry',
    mentions: 34100,
    changePercent: 41.5,
    sentiment: 'positive',
    sentimentScore: 84,
    velocity: 'very_high',
  },
  {
    id: 't-3',
    rank: 3,
    name: 'RealTimeDataAPI',
    category: 'Engineering',
    mentions: 22800,
    changePercent: 28.3,
    sentiment: 'positive',
    sentimentScore: 78,
    velocity: 'high',
  },
  {
    id: 't-4',
    rank: 4,
    name: 'SocialListening v2',
    category: 'Features',
    mentions: 17450,
    changePercent: 19.8,
    sentiment: 'neutral',
    sentimentScore: 65,
    velocity: 'high',
  },
  {
    id: 't-5',
    rank: 5,
    name: 'DashboardUX',
    category: 'Design',
    mentions: 12900,
    changePercent: 14.1,
    sentiment: 'positive',
    sentimentScore: 88,
    velocity: 'moderate',
  },
  {
    id: 't-6',
    rank: 6,
    name: 'PrivacyProtocols',
    category: 'Compliance',
    mentions: 9140,
    changePercent: -4.3,
    sentiment: 'neutral',
    sentimentScore: 58,
    velocity: 'moderate',
  },
];

export const mockDemographics: DemographicRegion[] = [
  { id: 'us', name: 'North America', code: 'NA', share: 38.4, mentions: 56940, growth: 12.4, x: 26, y: 35, radius: 24, sentiment: 82 },
  { id: 'eu', name: 'Western Europe', code: 'EU', share: 27.2, mentions: 40330, growth: 18.6, x: 52, y: 30, radius: 20, sentiment: 79 },
  { id: 'ap', name: 'Asia Pacific', code: 'APAC', share: 20.8, mentions: 30840, growth: 24.1, x: 78, y: 46, radius: 18, sentiment: 84 },
  { id: 'latam', name: 'Latin America', code: 'LATAM', share: 8.6, mentions: 12750, growth: 9.3, x: 34, y: 68, radius: 13, sentiment: 75 },
  { id: 'mea', name: 'Middle East & Africa', code: 'MEA', share: 5.0, mentions: 7430, growth: 14.2, x: 58, y: 55, radius: 11, sentiment: 72 },
];

export const mockInfluenceNodes: InfluenceNode[] = [
  {
    id: 'n-core',
    name: 'Syntra HQ',
    handle: '@SyntraAnalytics',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    role: 'Central Hub',
    reach: '850K Reach',
    affinity: 98,
    sentiment: 'positive',
    category: 'Brand',
    x: 50,
    y: 50,
    size: 32,
    isKeyVoice: true,
  },
  {
    id: 'n-1',
    name: 'Elena Rostova',
    handle: '@elena_ai',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    role: 'AI Researcher & Tech Lead',
    reach: '420K Reach',
    affinity: 92,
    sentiment: 'positive',
    category: 'Tech Lead',
    x: 28,
    y: 30,
    size: 24,
    isKeyVoice: true,
  },
  {
    id: 'n-2',
    name: 'Marcus Chen',
    handle: '@marcusdata',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    role: 'Product Strategist',
    reach: '310K Reach',
    affinity: 86,
    sentiment: 'positive',
    category: 'Product',
    x: 74,
    y: 28,
    size: 22,
    isKeyVoice: true,
  },
  {
    id: 'n-3',
    name: 'Sarah Jenkins',
    handle: '@jenkins_media',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    role: 'Growth Marketing Director',
    reach: '260K Reach',
    affinity: 89,
    sentiment: 'positive',
    category: 'Marketing',
    x: 78,
    y: 68,
    size: 20,
    isKeyVoice: true,
  },
  {
    id: 'n-4',
    name: 'Devon Patel',
    handle: '@devon_builds',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    role: 'Full-Stack Architect',
    reach: '185K Reach',
    affinity: 81,
    sentiment: 'positive',
    category: 'Engineering',
    x: 22,
    y: 72,
    size: 18,
    isKeyVoice: false,
  },
  {
    id: 'n-5',
    name: 'Aria Vance',
    handle: '@ariav_ux',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    role: 'Design Systems Lead',
    reach: '142K Reach',
    affinity: 85,
    sentiment: 'positive',
    category: 'Design',
    x: 48,
    y: 18,
    size: 17,
    isKeyVoice: false,
  },
  {
    id: 'n-6',
    name: 'Tariq Al-Mansoor',
    handle: '@tariq_analytics',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    role: 'Venture & Data Analyst',
    reach: '210K Reach',
    affinity: 79,
    sentiment: 'neutral',
    category: 'Venture',
    x: 52,
    y: 84,
    size: 18,
    isKeyVoice: false,
  },
];

export const mockInfluenceEdges: InfluenceEdge[] = [
  { id: 'e-1', source: 'n-core', target: 'n-1', weight: 4 },
  { id: 'e-2', source: 'n-core', target: 'n-2', weight: 3 },
  { id: 'e-3', source: 'n-core', target: 'n-3', weight: 3 },
  { id: 'e-4', source: 'n-core', target: 'n-4', weight: 2 },
  { id: 'e-5', source: 'n-core', target: 'n-5', weight: 2 },
  { id: 'e-6', source: 'n-core', target: 'n-6', weight: 2 },
  { id: 'e-7', source: 'n-1', target: 'n-5', weight: 1.5 },
  { id: 'e-8', source: 'n-2', target: 'n-3', weight: 2 },
  { id: 'e-9', source: 'n-4', target: 'n-6', weight: 1.5 },
];

export const mockSocialPosts: SocialPost[] = [
  {
    id: 'p-1',
    author: 'Elena Rostova',
    handle: '@elena_ai',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    verified: true,
    platform: 'twitter',
    content: 'Just deployed the newest analytics pipeline using Syntra. Processing 150k live social signals per second with sub-100ms latency. The sentiment clustering accuracy is remarkable.',
    timestamp: '3m ago',
    sentiment: 'positive',
    sentimentScore: 95,
    likes: 1420,
    reposts: 312,
    engagementScore: 9.6,
  },
  {
    id: 'p-2',
    author: 'Marcus Chen',
    handle: '@marcusdata',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    verified: true,
    platform: 'linkedin',
    content: 'Observing a clear 48% inflection point on community sentiment around generative developer toolchains this morning. Syntra Radar caught the vector 4 hours before mainstream news.',
    timestamp: '11m ago',
    sentiment: 'positive',
    sentimentScore: 89,
    likes: 840,
    reposts: 95,
    engagementScore: 8.8,
  },
  {
    id: 'p-3',
    author: 'OpenData_Dev',
    handle: '@opendata_dev',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    verified: false,
    platform: 'reddit',
    content: 'Benchmark testing social intelligence engines: Syntra is consistently reporting net sentiment with lower noise variance compared to older legacy scrapers.',
    timestamp: '24m ago',
    sentiment: 'positive',
    sentimentScore: 82,
    likes: 310,
    reposts: 42,
    engagementScore: 7.9,
  },
  {
    id: 'p-4',
    author: 'Sarah Jenkins',
    handle: '@jenkins_media',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    verified: true,
    platform: 'twitter',
    content: 'Brand safety monitoring update: false-negative alerts down by 32% since shifting to real-time semantic radar. Team reaction has been overwhelmingly confident.',
    timestamp: '42m ago',
    sentiment: 'positive',
    sentimentScore: 91,
    likes: 980,
    reposts: 174,
    engagementScore: 9.1,
  },
  {
    id: 'p-5',
    author: 'CloudOps Weekly',
    handle: '@cloudops_watch',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    verified: false,
    platform: 'reddit',
    content: 'Evaluating webhook latency across analytics providers. The Syntra ingestion endpoint responds consistently in 18ms from both US-East and Frankfurt nodes.',
    timestamp: '1h ago',
    sentiment: 'neutral',
    sentimentScore: 68,
    likes: 185,
    reposts: 16,
    engagementScore: 6.4,
  },
];

export const mockForecastData: ForecastPoint[] = [
  { date: 'Sep 13', actualMentions: 148290, predictedMentions: 148290, upperConfidence: 154000, lowerConfidence: 142000, predictedSentiment: 78.4 },
  { date: 'Sep 14', actualMentions: undefined, predictedMentions: 156400, upperConfidence: 166000, lowerConfidence: 148000, predictedSentiment: 79.2 },
  { date: 'Sep 15', actualMentions: undefined, predictedMentions: 168200, upperConfidence: 181000, lowerConfidence: 155000, predictedSentiment: 80.5 },
  { date: 'Sep 16', actualMentions: undefined, predictedMentions: 182000, upperConfidence: 198000, lowerConfidence: 167000, predictedSentiment: 81.8 },
  { date: 'Sep 17', actualMentions: undefined, predictedMentions: 194500, upperConfidence: 215000, lowerConfidence: 174000, predictedSentiment: 82.3 },
  { date: 'Sep 18', actualMentions: undefined, predictedMentions: 206000, upperConfidence: 232000, lowerConfidence: 181000, predictedSentiment: 83.1 },
  { date: 'Sep 19', actualMentions: undefined, predictedMentions: 219800, upperConfidence: 250000, lowerConfidence: 190000, predictedSentiment: 83.7 },
];
